-- Add song metadata columns and backfill from repertoire export

BEGIN;

ALTER TABLE songs
  ADD COLUMN IF NOT EXISTS artist text,
  ADD COLUMN IF NOT EXISTS bpm integer,
  ADD COLUMN IF NOT EXISTS original_key text,
  ADD COLUMN IF NOT EXISTS my_key text,
  ADD COLUMN IF NOT EXISTS capo integer;

WITH updates (title, artist, bpm, original_key, my_key, capo, length_text) AS (
  VALUES
    ('God Only Knows (Instrumental)', 'The Beach Boys', NULL, NULL, NULL, NULL, NULL),
    ('Babylon (UK Radio Mix)', 'David Gray', 112, 'Eb', 'Eb', 1, '03:31'),
    ('White Mirror', 'Farhan Mannan', 128, 'B', 'B', NULL, '03:30'),
    ('River', 'Leon Bridges', 128, 'Ab', 'Ab', 1, '04:00'),
    ('Torn', 'Natalie Imbruglia', 96, 'F', 'C', NULL, '04:05'),
    ('London Mine', 'Joy Crookes', 115, 'D', 'C', NULL, '03:43'),
    ('He Can Only Hold Her', 'Amy Winehouse', 98, '~C', 'G', NULL, '02:46'),
    ('Quiet Eye', 'Farhan Mannan', 126, 'G', 'G', NULL, '04:11'),
    ('Blinding Lights', 'The Weeknd', 171, 'E', 'C', NULL, '03:20'),
    ('Ride Or Die', 'Farhan Mannan', NULL, NULL, NULL, NULL, NULL),
    ('all the good girls go to hell', 'Billie Eilish', 185, 'B', 'G', NULL, '02:49'),
    ('Your Song', 'Elton John', 128, 'Eb', 'Eb', 1, '04:02'),
    ('Speak Your Language', 'Farhan Mannan', 119, 'D', 'D', NULL, '04:18'),
    ('Hotel California', 'Eagles', 147, 'D', 'C', 2, '06:31'),
    ('What A Difference A Day Made', 'Jamie Cullum', 97, 'F', 'F', NULL, '05:10'),
    ('Dancing In The Dark', 'Bruce Springsteen', 149, 'B', 'A', NULL, '04:01'),
    ('I Still Haven’t Found What I’m Looking For', 'U2', 101, 'Db', 'A', NULL, '04:37'),
    ('Brown Eyed Girl', 'Van Morrison', 151, 'G', 'G', NULL, '03:03'),
    ('What Is This Thing Called Love', 'Ella Fitzgerald', 142, 'G', NULL, NULL, '02:05'),
    ('Hide', 'Farhan Mannan', NULL, NULL, NULL, NULL, NULL),
    ('(What A) Wonderful World', 'Sam Cooke', 129, 'B', 'A', 2, '02:06'),
    ('The Nearness Of You', 'Ella Fitzgerald', NULL, NULL, NULL, NULL, NULL),
    ('Fly Away', 'Lenny Kravitz', 80, 'A', 'G', NULL, '03:41'),
    ('Don’t Look Back In Anger', 'Oasis', 82, '~C', 'C', NULL, '04:50'),
    ('Sittin’ On The Dock Of The Bay', 'Otis Redding', 104, 'G', 'G', NULL, '02:44'),
    ('Why Does It Always Rain On Me', 'Travis', 108, 'Eb', 'Eb', 1, '04:25'),
    ('Back To Black', 'Amy Winehouse', NULL, NULL, 'F', NULL, NULL),
    ('Every Breath You Take', 'The Police', 117, 'Ab', 'Ab', 1, '04:14'),
    ('Moondance', 'Van Morrison', 67, 'C', NULL, NULL, '04:34'),
    ('Stir It Up', 'Bob Marley', 147, 'A', 'A', NULL, '05:32'),
    ('Believe', 'Cher', 133, 'Gb', 'D', NULL, '03:59'),
    ('Hometown Glory', 'Adele', NULL, NULL, NULL, NULL, NULL),
    ('Rocky Raccoon', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Nothing Man', 'Bruce Springsteen', 110, 'E', 'E', NULL, '04:20'),
    ('Born To Run', 'Bruce Springsteen', 146, 'E', NULL, NULL, '04:30'),
    ('Stand Up', 'Cynthia Erivo', NULL, NULL, NULL, NULL, NULL),
    ('Sail Away', 'David Gray', NULL, NULL, NULL, NULL, NULL),
    ('New Kid In Town', 'Eagles', 107, 'E', 'E', NULL, '05:05'),
    ('Castle On The Hill', 'Ed Sheeran', 135, 'D', NULL, NULL, '04:21'),
    ('BTSTU', 'Jai Paul', 90, 'Db', 'G', NULL, '03:29'),
    ('Wisemen', 'James Blunt', 152, 'Bb', NULL, NULL, '03:42'),
    ('You Give Me Something', 'James Morrison', NULL, NULL, NULL, NULL, NULL),
    ('Gravity', 'John Mayer', NULL, NULL, NULL, NULL, NULL),
    ('Bring It On Home', 'Sam Cooke', NULL, NULL, NULL, NULL, NULL),
    ('God Only Knows', 'The Beach Boys', NULL, NULL, NULL, NULL, NULL),
    ('Let It Be', 'The Beatles', NULL, 'C', NULL, NULL, NULL),
    ('All My Loving', 'The Beatles', 78, 'E', 'E', NULL, '02:08'),
    ('Nowhere Man', 'The Beatles', 121, 'E', 'E', NULL, '02:44'),
    ('Get Back', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Here Comes The Sun', 'The Beatles', 129, 'A', 'A', 7, '03:06'),
    ('Werewolves Of London', 'Warren Zevon', 104, 'G', 'A', NULL, '03:29'),
    ('Dancing Queen', 'ABBA', 101, 'A', 'A', NULL, '03:50'),
    ('Forever Young', 'Alphaville', 137, 'A', 'A', NULL, '03:47'),
    ('Redemption Song', 'Bob Marley', 116, 'G', 'G', NULL, '03:54'),
    ('Wrecking Ball', 'Bruce Springsteen', 118, 'F', 'F', 1, '05:48'),
    ('If I Should Fall Behind', 'Bruce Springsteen', NULL, NULL, NULL, NULL, NULL),
    ('Racing In The Street', 'Bruce Springsteen', 87, 'F', NULL, NULL, '06:53'),
    ('Girls Just Want To Have Fun', 'Cyndi Lauper', 120, 'Gb', 'Gb', NULL, '03:58'),
    ('Babylon', 'David Gray', 112, 'Eb', 'Eb', 1, '04:26'),
    ('Accumulates', 'David Gray', NULL, NULL, NULL, NULL, NULL),
    ('Nemesis', 'David Gray', 124, 'A', NULL, NULL, '05:27'),
    ('Say Hello, Wave Goodbye', 'David Gray', 160, 'A', NULL, NULL, '08:58'),
    ('End Of The Innocence', 'Don Henley', 117, 'Ab', 'Ab', 1, '05:18'),
    ('Take It Easy', 'Eagles', 139, 'G', 'G', NULL, '03:32'),
    ('My People', 'Eg', NULL, NULL, NULL, NULL, NULL),
    ('Hound Dog', 'Elvis Presley', 87, 'C', 'C', NULL, '02:16'),
    ('Valentine', 'Farhan Mannan', 76, 'C', 'Ab', 1, '03:25'),
    ('Were You Ever Really Mine', 'Farhan Mannan', NULL, NULL, NULL, NULL, NULL),
    ('Baker Street', 'Gerry Rafferty', NULL, NULL, NULL, NULL, NULL),
    ('Crazy', 'Gnarls Barkley', NULL, NULL, NULL, NULL, NULL),
    ('Iris', 'Goo Goo Dolls', 156, 'Bm', NULL, NULL, '03:35'),
    ('Take Me To Church', 'Hozier', 129, 'E', 'E', NULL, '04:02'),
    ('Doctor My Eyes', 'Jackson Browne', NULL, NULL, NULL, NULL, NULL),
    ('Only Children', 'Jason Isbell', 89, 'G', 'G', NULL, '03:57'),
    ('I’m Yours', 'Jason Mraz', 75, 'B', NULL, NULL, '03:39'),
    ('Take Me Home, Country Roads', 'John Denver', 164, 'A', 'A', NULL, '03:18'),
    ('Slow Dancing In A Burning Room', 'John Mayer', 134, 'E', 'E', NULL, '04:02'),
    ('Born To Die', 'Lana Del Rey', 86, 'G', NULL, NULL, '04:45'),
    ('Hallelujah', 'Leonard Cohen', 171, 'C', 'C', NULL, '04:37'),
    ('Sirens', 'Lola Marsh', NULL, NULL, NULL, NULL, NULL),
    ('Feelin’ Good', 'Nina Simone', NULL, NULL, NULL, NULL, NULL),
    ('Live Forever', 'Oasis', NULL, NULL, NULL, NULL, NULL),
    ('Little By Little', 'Oasis', 146, 'D', NULL, NULL, '04:54'),
    ('Me And Julio Down By The Schoolyard', 'Paul Simon', 105, 'A', 'A', NULL, '02:45'),
    ('Californication', 'Red Hot Chili Peppers', 96, 'C', NULL, NULL, '05:30'),
    ('Under The Bridge', 'Red Hot Chili Peppers', 85, 'E', NULL, NULL, '04:24'),
    ('Feel', 'Robbie Williams', NULL, NULL, NULL, NULL, NULL),
    ('Your Love Is King', 'Sade', 135, 'A', NULL, NULL, '03:41'),
    ('Mrs Robinson', 'Simon & Garfunkel', 92, 'A', NULL, NULL, '04:02'),
    ('Hedonism', 'Skunk Anansie', NULL, NULL, NULL, NULL, NULL),
    ('Handbags & Gladrags', 'Stereophonics', NULL, NULL, NULL, NULL, NULL),
    ('Everybody Wants To Rule The World', 'Tears For Fears', 112, 'G', 'G', NULL, '04:11'),
    ('Tribute', 'Tenacious D', NULL, NULL, NULL, NULL, NULL),
    ('Robbers', 'The 1975', 100, 'B', NULL, NULL, '04:15'),
    ('Chocolate', 'The 1975', 100, 'B', NULL, NULL, '03:45'),
    ('God Only Knows', 'The Beach Boys', NULL, NULL, NULL, NULL, NULL),
    ('The Night Before', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('You’ve Got To Hide Your Love Away', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('I’ve Just Seen A Face', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Two Of Us', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Ob-La-Di, Ob-La-Da', 'The Beatles', 113, 'Bb', 'Bb', NULL, '03:09'),
    ('Don’t Let Me Down', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('When I’m Sixty-Four', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('I’m So Tired', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Hello, Goodbye', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Help!', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Another Girl', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Ticket To Ride', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Act Naturally', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('I Need You', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('If I Fell', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('The Long And Winding Road', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Things We Said Today', 'The Beatles', NULL, NULL, NULL, NULL, NULL),
    ('Yesterday', 'The Beatles', 97, 'F', 'F', NULL, '02:06'),
    ('Friday I’m In Love', 'The Cure', 136, 'D', NULL, NULL, '03:38'),
    ('Seaside', 'The Kooks', 129, 'Db', 'Db', NULL, '01:39'),
    ('Love Is All Around', 'Wet Wet Wet', 170, 'Bb', 'Bb', NULL, '03:58'),
    ('Teenage Dirtbag', 'Wheatus', NULL, NULL, NULL, NULL, NULL),
    ('Leave Right Now', 'Will Young', NULL, NULL, NULL, NULL, NULL),
    ('Easy On Me', 'Adele', NULL, NULL, NULL, NULL, NULL),
    ('Billy Jack', 'Curtis Mayfield', NULL, NULL, NULL, NULL, NULL),
    ('New Leaf', 'Farhan Mannan', NULL, 'G', 'Eb', NULL, NULL),
    ('Fade Into You', 'Mazzy Star', NULL, 'A', 'E', NULL, NULL),
    ('Wetsuit', 'The Vaccines', NULL, 'F', 'F', 1, NULL),
    ('6th Avenue Heartache', 'The Wallflowers', NULL, 'F', 'F', 1, NULL),
    ('Dude Looks Like A Lady', 'Aerosmith', 126, 'A', 'A', NULL, '04:26'),
    ('Waitin’ On A Sunny Day', 'Bruce Springsteen', 106, 'C', 'C', NULL, '04:16'),
    ('Bags', 'Clairo', 105, 'Db', 'Db', NULL, '04:21'),
    ('Sleep On The Left Side', 'Cornershop', 92, 'G', 'G', NULL, '04:06'),
    ('Everywhere That *** Army Roam', 'Cornershop', 122, 'D', 'D', NULL, '05:09'),
    ('Twisted', 'Farhan Mannan', 75, 'D', 'D', NULL, '03:29'),
    ('Activation', 'Farhan Mannan', 119, 'G', 'G', NULL, '03:45'),
    ('Heat Waves', 'Glass Animals', 81, 'B', 'B', NULL, '03:59'),
    ('Feel Good Inc.', 'Gorillaz', 139, 'Gb', 'Gb', NULL, '03:43'),
    ('Jasmine', 'Jai Paul', 90, 'Eb', 'Eb', NULL, '04:13'),
    ('Purple Haze', 'Jimi Hendrix', 109, 'E', 'E', NULL, '02:51'),
    ('Hounds Of Love', 'Kate Bush', 146, 'F', 'F', NULL, '03:03'),
    ('Suddenly I See', 'KT Tunstall', 100, 'C', 'A', NULL, '03:22'),
    ('Paper Planes', 'M.I.A.', 172, 'D', 'D', NULL, '03:25'),
    ('Champagne Supernova', 'Oasis', 150, 'D', 'D', NULL, '07:31'),
    ('Half The World Away', 'Oasis', 105, 'C', 'C', NULL, '04:27'),
    ('Slip Slidin’ Away', 'Paul Simon', 121, 'Ab', 'Ab', 1, '04:45'),
    ('Where The Frequencies Run Deep And Wild', 'Razorlight', 149, 'D', 'C', NULL, '03:07'),
    ('Wishing Well', 'Sananda Maitreya', 105, 'Bb', 'Bb', NULL, '03:30'),
    ('Crazy', 'Seal', 103, 'B', 'B', NULL, '05:57'),
    ('Fields Of Gold', 'Sting', 104, 'D', 'D', NULL, '03:42'),
    ('Can’t Buy Me Love', 'The Beatles', 171, 'C', 'C', NULL, '02:12'),
    ('Naive', 'The Kooks', 103, 'Ab', 'Ab', NULL, '03:24'),
    ('Three Marlenas', 'The Wallflowers', 107, 'Ab', 'Ab', NULL, '04:59'),
    ('Whiskey In The Jar', 'Thin Lizzy', 128, 'G', 'E', NULL, '05:46')
)
UPDATE songs
SET artist = COALESCE(updates.artist, songs.artist),
    bpm = COALESCE(updates.bpm, songs.bpm),
    original_key = COALESCE(updates.original_key, songs.original_key),
    my_key = COALESCE(updates.my_key, songs.my_key),
    capo = COALESCE(updates.capo, songs.capo),
    length = COALESCE(
      CASE
        WHEN updates.length_text IS NULL THEN songs.length
        WHEN updates.length_text ~ '^[0-9]+:[0-9]{2}$' THEN (updates.length_text || ' minutes')::interval
        ELSE songs.length
      END,
      songs.length
    )
FROM updates
WHERE songs.title = updates.title;

COMMIT;
